<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AggregateRootes\Carts\Enum\" />
    <Folder Include="AggregateRootes\Carts\Value Object\" />
    <Folder Include="AggregateRootes\Orders\Value Object\" />
    <Folder Include="AggregateRootes\Products\Enum\" />
    <Folder Include="AggregateRootes\Products\Value Object\" />
    <Folder Include="AggregateRootes\Reviews\Enum\" />
  </ItemGroup>

</Project>
